#!/usr/bin/env python3
"""Merge AI votes into bills.json"""
import json
from pathlib import Path

DATA_FILE = Path(__file__).parent.parent / "data" / "bills.json"

# All votes from the subagents
votes = [
  {"id": "SB1501", "vote": "no", "reasoning": "This bill uses a tax increment financing mechanism to redirect payroll withholding taxes from the General Fund to subsidize a professional sports arena, effectively making taxpayers backstop a private NBA franchise's lease. Diverting General Fund-equivalent tax revenues to benefit a private sports team is not a sound use of public money when Oregon faces pressing needs in education, housing, and healthcare."},
  {"id": "SB1502", "vote": "yes", "reasoning": "This is a narrow, low-cost measure that directs the Secretary of State to file recommendations for improving Oregon's campaign finance limitations system. It promotes democratic accountability and has no fiscal impact of its own."},
  {"id": "SB1504", "vote": "yes", "reasoning": "Expanding permissible forms of epinephrine delivery in schools beyond auto-injection (e.g., to intranasal devices) is a sensible, evidence-based update that improves emergency response options for students with severe allergies at no significant cost."},
  {"id": "SB1505", "vote": "yes", "reasoning": "Establishing a workforce standards board for home and community-based care workers addresses a real workforce shortage in a sector critical to aging and disabled Oregonians. The bill includes fiscal guardrails — standards cannot take effect until the Legislature appropriates funding."},
  {"id": "SB1506", "vote": "yes", "reasoning": "Commissioning a study on how other states fund their labor agencies is a prudent and low-cost exercise in fiscal planning. The bill sunsets automatically in 2028, limiting any ongoing administrative burden."},
  {"id": "SB1507", "vote": "no", "reasoning": "This bill reduces income taxes, corporate taxes, and the estate tax conditioned on Oregon enacting a retail sales tax by 2030. The tax reduction provisions are incomplete as drafted (replacement rate brackets are left blank), making the bill technically deficient. The policy involves significant revenue risk and regressive tradeoffs."},
  {"id": "SB1508", "vote": "yes", "reasoning": "Directing the Secretary of State to study elections and report to interim legislative committees is a minimal, sunsetted measure that costs little and could produce useful information for future election policy improvements."},
  {"id": "SB1509", "vote": "yes", "reasoning": "This bill implements the U.S. Supreme Court's ruling in Chiafalo v. Washington (2020) by codifying binding elector pledges and creating a clear vacancy mechanism when a presidential elector casts a faithless ballot. It strengthens democratic integrity."},
  {"id": "SB1510", "vote": "yes", "reasoning": "This is a technical corrections bill that updates tax code terminology to match federal law changes, removes an expired sunset on the earned income tax credit, and expands a film production tax credit. The changes are narrow, well-reasoned, and fiscally modest."},
  {"id": "SB1511", "vote": "yes", "reasoning": "Directing the Legislative Revenue Officer to study the estate tax and review options for modifying the exemption threshold and rates is a prudent, zero-cost measure that will inform evidence-based tax policy."},
  {"id": "SB1512", "vote": "yes", "reasoning": "This bill strengthens the Prosperity 10,000 workforce development program by shifting administration through local workforce development boards and adding grant criteria that emphasize employer engagement and leveraging federal funds."},
  {"id": "SB1513", "vote": "yes", "reasoning": "This bill provides a temporary compliance extension for real estate teams to adjust their team names to comply with existing law, giving them until July 1, 2027. It is a narrow, practical measure that avoids abrupt disruption."},
  {"id": "SB1514", "vote": "no", "reasoning": "Repealing the objective reasonableness standard would remove an important legal guardrail that balances local government authority with the rights of people experiencing homelessness. Without this standard, cities could enforce overly punitive restrictions with no consistent statewide check."},
  {"id": "SB1515", "vote": "yes", "reasoning": "This bill strengthens protections for the wrongfully convicted by clarifying compensation eligibility, making certificates of innocence mandatory, and creating a new post-conviction relief pathway for convictions tainted by discredited forensic science."},
  {"id": "SB1516", "vote": "yes", "reasoning": "Expanding aggravated harassment to cover threats against public officials made in connection with their duties addresses a genuine and growing problem of official intimidation. The bill retains First Amendment compatibility by requiring a reasonable-alarm standard."},
  {"id": "SB1517", "vote": "yes", "reasoning": "This bill strikes a reasonable balance in ski liability law: it allows operators to require negligence releases while explicitly prohibiting releases for gross negligence, equipment-related injuries, and violations of statutory duties. It also requires an opt-out option for skiers."},
  {"id": "SB1518", "vote": "yes", "reasoning": "Directing BOLI to study worker protection issues and report by September 2027 is a low-cost, information-gathering measure. The automatic sunset on January 2, 2028 prevents it from becoming a permanent mandate."},
  {"id": "SB1519", "vote": "yes", "reasoning": "Restructuring temporary total disability compensation to use a tiered rate provides higher replacement rates for lower-wage workers, who are most economically vulnerable when injured, while maintaining fiscal discipline for higher earners."},
  {"id": "SB1520", "vote": "yes", "reasoning": "Authorizing the Employment Department director to adopt accounting rules for the Paid Family and Medical Leave Insurance Fund addresses a practical administrative need. The bill expressly prohibits altering the contribution rate structure set by the legislature."},
  {"id": "SB1521", "vote": "yes", "reasoning": "Requiring Portland-area cities to conduct economic analyses before mandating inclusionary housing makes affordable housing requirements more legally durable and economically rational, reducing the risk that mandates simply deter development."},
  {"id": "SB1522", "vote": "yes", "reasoning": "Directing OHCS to study housing and report to the legislature by September 2027 is a minimal-cost, information-gathering step with a built-in sunset. Oregon faces a serious housing shortage, and a focused study can support evidence-based policymaking."},
  {"id": "SB1523", "vote": "yes", "reasoning": "This bill protects tenant rights by guaranteeing non-electronic alternatives for all essential tenancy functions and prohibiting mandatory electronic-only payment requirements. It is particularly important for elderly, disabled, or low-income tenants who may lack reliable internet access."},
  {"id": "SB1524", "vote": "no", "reasoning": "Allocating a continuing stream of lottery revenues to support horse racing is a questionable use of public funds that benefits a narrow commercial interest rather than the general public. Lottery proceeds should be directed toward broad public benefits."},
  {"id": "SB1525", "vote": "yes", "reasoning": "This bill establishes a well-structured Blue Economy Task Force with diverse stakeholder representation and a clear sunset date, and authorizes the Oregon Ocean Science Trust to form a nonprofit. Both are low-cost, high-potential-benefit actions."},
  {"id": "SB1526", "vote": "yes", "reasoning": "This bill creates a pathway to form a clean energy financing nonprofit, but wisely conditions action on securing at least $2 million in grant funding first, avoiding speculative state expenditures. Annual legislative reporting ensures oversight."},
  {"id": "SB1527", "vote": "yes", "reasoning": "Eliminating cost-sharing on cervical cancer screenings is a sound preventive health policy — early detection reduces downstream treatment costs and saves lives. The bill aligns with USPSTF evidence-based recommendations."},
  {"id": "SB1528", "vote": "no", "reasoning": "This bill is dangerously vague — it directs OHA to 'study health care' with no defined scope, methodology, or specific questions. A one-sentence directive to study an entire sector is not meaningful legislation and wastes agency resources."},
  {"id": "SB1529", "vote": "no", "reasoning": "This bill is identical to SB1528 — it directs OHA to 'study health care' with no scope or defined deliverables, and appears to be a duplicate placeholder bill. Passing two identical unfocused bills is redundant."},
  {"id": "SB1530", "vote": "yes", "reasoning": "Expanding the aggravated harassment statute to protect public officials from credible threats is a reasonable public safety measure. The requirement that the threat be objectively alarm-inducing provides sufficient limiting principles."},
  {"id": "SB1531", "vote": "yes", "reasoning": "Studying the feasibility of funding emergency medical services through a universal health care model is a prudent, low-cost step toward addressing EMS funding sustainability — a genuine crisis in rural Oregon."},
  {"id": "SB1532", "vote": "yes", "reasoning": "This bill addresses gaps in protections for vulnerable adults and children in care by adding procedural requirements before imposing license conditions on long-term care facilities and requiring consent forms for electronic monitoring."},
  {"id": "SB1533", "vote": "yes", "reasoning": "This bill strengthens the Oregon Foster Children's Bill of Rights by adding specific enumerated rights, shortening the notice period from 60 to 7 days, and clarifying sibling contact protections."},
  {"id": "SB1534", "vote": "yes", "reasoning": "This bill fills important gaps in protections for children in care by clarifying definitions of abuse, strengthening child-caring agency licensing, and modifying out-of-state placement rules."},
  {"id": "SB1535", "vote": "no", "reasoning": "Like SB1528 and SB1529, this is a one-sentence directive to 'study child care' with no defined scope or methodology. A bill this vague does not constitute responsible legislating."},
  {"id": "SB1536", "vote": "yes", "reasoning": "Studying the adequacy of assessments in Oregon public schools is a reasonable and focused inquiry with a clear deliverable. This is a low-cost, potentially high-value study that could inform meaningful education reform."},
  {"id": "SB1537", "vote": "yes", "reasoning": "This bill improves transparency and community college governance by requiring public email addresses for board members and adding a student nonvoting representative to boards, giving students a meaningful voice."},
  {"id": "SB1538", "vote": "yes", "reasoning": "This bill protects the right to education for all students regardless of immigration status, codifying existing constitutional obligations while adding practical school-level protocols for responding to immigration enforcement."},
  {"id": "SB1539", "vote": "yes", "reasoning": "This bill addresses a practical workforce need by allowing trained individuals to perform cattle pregnancy verification without a full veterinary license, reducing costs for agricultural operations while still requiring relevant training."},
  {"id": "SB1540", "vote": "yes", "reasoning": "This bill addresses a critical consumer protection gap in Oregon's wildfire insurance market by requiring insurers to disclose risk scores, explain how mitigation actions affect premiums, and provide an appeals process."},
  {"id": "SB1541", "vote": "no", "reasoning": "While addressing climate costs is legitimate, this bill imposes strict retroactive liability on fossil fuel companies for global emissions going back to 1995, raising significant constitutional and jurisdictional concerns. The causal attribution methodology is inherently contested and litigation-prone."},
  {"id": "SB1542", "vote": "yes", "reasoning": "This bill creates accountability and transparency in Oregon's transportation spending by requiring a 10-year capital investment plan with a scored, ranked project prioritization methodology that prioritizes safety and preservation."},
  {"id": "SB1543", "vote": "yes", "reasoning": "Expanding the Oregon Transportation Commission from five to seven members with regional representation and requiring a formal debt financing management policy are sound governance reforms for a commission overseeing billions."},
  {"id": "SB1544", "vote": "yes", "reasoning": "This is a modest, low-cost study bill that directs ODOT to examine uniform standards for speed bump height and markings. It has a built-in sunset and requires a legislative report."},
  {"id": "SB1545", "vote": "yes", "reasoning": "Corner crossing — stepping across the point where two public land parcels meet — has been a long-standing issue preventing access to landlocked public lands. This bill provides a balanced solution granting immunity from trespass suits for foot traffic that causes no harm."},
  {"id": "SB1546", "vote": "yes", "reasoning": "This bill addresses a genuine public health concern by requiring AI companion platforms to disclose their artificial nature, implement suicide and self-harm detection protocols, and apply additional protections for minors."},
  {"id": "SB1547", "vote": "yes", "reasoning": "Creating a new licensed behavioral health practitioner credential addresses Oregon's documented shortage of behavioral health workers by establishing a mid-level license for prevention and brief intervention services."},
  {"id": "SB1548", "vote": "yes", "reasoning": "This bill takes measured steps to improve public health around cannabis by requiring individual wrapping of edibles, mandating health-warning labels, and allowing local governments to establish buffer zones."},
  {"id": "SB1549", "vote": "no", "reasoning": "This bill raises the political contribution tax credit from $50/$100 to $1,000/$2,000 — a 20-fold increase that primarily benefits wealthier donors and creates significant foregone revenue for the state. The dramatic increase is fiscally irresponsible."},
  {"id": "SB1550", "vote": "yes", "reasoning": "This bill closes a critical gap in death investigations by requiring law enforcement to interview family members and pursue autopsies when red-flag indicators of domestic violence or child abuse are present in suspected suicide/overdose deaths."},
  {"id": "SB1551", "vote": "yes", "reasoning": "This bill prevents HOA deed restrictions from blocking fire-hardened building materials, a commonsense public safety measure given Oregon's growing wildfire risk. It still allows HOAs to apply aesthetic guidelines within reason."},
  {"id": "SB1552", "vote": "yes", "reasoning": "This bill requires county clerks to notify property owners when instruments affecting their title are recorded, providing a simple and effective protection against deed fraud and title theft."},
  {"id": "SB1553", "vote": "yes", "reasoning": "This bill provides important consumer protections by prohibiting electric utilities found negligent in causing wildfires from passing their litigation costs onto ratepayers. It appropriately holds negligent utilities financially accountable."},
  {"id": "SB1554", "vote": "no", "reasoning": "While the underlying principle that live-born infants deserve medical care is shared, this bill is primarily aimed at restricting abortion-related medical practice and introduces punitive mechanisms that could chill legitimate clinical decision-making. It is redundant with existing federal law."},
  {"id": "SB1555", "vote": "yes", "reasoning": "This bill streamlines Oregon's constitutional reporting requirement for public education funding by replacing duplicative oversight bodies with a more direct cost-model approach. It preserves accountability while reducing bureaucratic overhead."},
  {"id": "SB1556", "vote": "yes", "reasoning": "This bill consolidates rules for non-attorney representation before the Oregon Tax Court magistrate division, making it easier for taxpayers to navigate disputes without necessarily hiring an attorney. It improves access to justice."},
  {"id": "SB1557", "vote": "yes", "reasoning": "This bill modernizes Oregon's contempt proceeding statutes, improving procedural clarity and fairness. Key improvements include explicit rights to counsel and appropriate default judgment procedures."},
  {"id": "SB1558", "vote": "no", "reasoning": "While this bill makes some positive adjustments to hospital nurse staffing law, the change increasing the medical-surgical nurse-to-patient ratio from 4 to 5 patients per nurse is a step backward for patient safety. Research consistently links lower ratios with better outcomes."},
  {"id": "SB1559", "vote": "no", "reasoning": "This bill directs OHA to 'study health care' with no defined scope, methodology, or specific questions. Such an unfocused mandate is an inefficient use of state agency resources and provides no meaningful policy direction."},
  {"id": "SB1560", "vote": "no", "reasoning": "This bill removes county authority to impose reasonable regulations on the physical characteristics of places of worship. Eliminating routine land use oversight raises equal treatment concerns and treats religious institutions more favorably without compelling justification."},
  {"id": "SB1561", "vote": "yes", "reasoning": "This bill creates a streamlined administrative pathway for homeowners to rebuild dwellings destroyed by natural disasters, bypassing the often-slow land use process. It includes reasonable safeguards limiting size increases to 25%."},
  {"id": "SB1562", "vote": "yes", "reasoning": "This bill gives local governments more flexibility in allocating transient lodging tax revenue, shifting the required tourism minimum from 70% to 40%. The added biennial reporting requirement improves transparency."},
  {"id": "SB1563", "vote": "yes", "reasoning": "This bill creates a state-level civil rights cause of action for violations of the Oregon Constitution by persons acting under color of law, mirroring the federal Section 1983 framework. It provides an important additional remedy for rights violations."},
  {"id": "SB1564", "vote": "yes", "reasoning": "This bill adds land to Woodburn's urban growth boundary with a meaningful 30% affordable housing requirement for 60 years. Woodburn has significant housing needs and the affordable housing mandate justifies the statutory override."},
  {"id": "SB1565", "vote": "yes", "reasoning": "This bill raises snowmobile registration fees from $10 to $30 to better fund trails and related services. The increase is modest and ensures those who use specific recreational resources help fund their maintenance."},
  {"id": "SB1566", "vote": "yes", "reasoning": "This bill updates Oregon's prevailing wage law exemption for affordable housing, expanding height limits and income targeting. Oregon faces a severe housing shortage and prevailing wage requirements significantly increase construction costs."},
  {"id": "SB1567", "vote": "yes", "reasoning": "This bill authorizes below-market bridge loans for mixed-income housing projects. The revolving loan fund structure is fiscally sound and the bill includes appropriate rule-making requirements for eligibility."},
  {"id": "SB1568", "vote": "yes", "reasoning": "This bill establishes minimum coverage standards for doula services and requires coverage for lactation counselors. Evidence strongly supports the benefits of doula support in improving maternal and infant health outcomes."},
  {"id": "SB1569", "vote": "yes", "reasoning": "This bill extends police officer PERS classification to forensic scientists, evidence technicians, and other law-enforcement-adjacent roles. The classifications are prospective only, limiting fiscal impact while helping recruitment and retention."},
]

# Build vote lookup
vote_map = {v["id"]: {"vote": v["vote"], "reasoning": v["reasoning"]} for v in votes}

# Load and update bills
bills = json.loads(DATA_FILE.read_text())
for bill in bills:
    if bill["id"] in vote_map:
        bill["vote"] = vote_map[bill["id"]]

DATA_FILE.write_text(json.dumps(bills, indent=2))

yes_count = sum(1 for b in bills if b["vote"]["vote"] == "yes")
no_count = sum(1 for b in bills if b["vote"]["vote"] == "no")
print(f"Updated {len(vote_map)} votes: {yes_count} yes, {no_count} no")
