#!/usr/bin/env python3
"""Merge AI votes into bills.json"""
import json
from pathlib import Path

DATA_FILE = Path(__file__).parent.parent / "data" / "bills.json"

# All votes from the subagents (re-run with unbiased prompt)
votes = [
  {"id": "SB1501", "vote": "no", "reasoning": "This bill authorizes the state to enter into agreements to own and operate the Moda Center and creates a dedicated fund seeded by redirecting existing General Fund tax revenues from arena-area workers to subsidize what is essentially a private sports venue. Using public funds and tax revenue to support a professional basketball arena sets a problematic precedent of socializing costs while privatizing profits."},
  {"id": "SB1502", "vote": "yes", "reasoning": "This bill simply directs the Secretary of State to file a pre-session legislative measure with recommendations for refining the campaign finance limitation system that Oregon began implementing in 2024. It is a low-cost, procedural step that advances democratic accountability and allows the legislature to course-correct based on real implementation experience."},
  {"id": "SB1504", "vote": "yes", "reasoning": "This bill modernizes epinephrine administration rules in schools by allowing delivery methods beyond injections, such as intranasal devices, and broadens training requirements accordingly. Expanding the range of permissible delivery methods for a life-saving medication improves access and flexibility for students with severe allergies at minimal cost and risk."},
  {"id": "SB1505", "vote": "yes", "reasoning": "This bill establishes a Workforce Standards Board for home and community-based services workers, a chronically underpaid sector essential to Oregon's aging and disability populations. The bill includes meaningful fiscal guardrails — requiring fiscal impact analysis, legislative appropriation before standards take effect, and CMS approval where needed."},
  {"id": "SB1506", "vote": "yes", "reasoning": "This is a narrow, low-cost study bill directing the Legislative Policy and Research Director to examine how labor agencies in other states are funded and recommend a sustainable funding source for the Bureau of Labor and Industries. The bill sunsets automatically in 2028."},
  {"id": "SB1507", "vote": "no", "reasoning": "This bill reduces income taxes, corporate taxes, estate taxes, and the corporate activity tax, making those reductions contingent on Oregon enacting a statewide retail sales tax. Oregon voters have repeatedly rejected a sales tax, making the operative conditions unlikely to materialize, and conditioning broad tax cuts on a regressive sales tax raises equity concerns."},
  {"id": "SB1508", "vote": "yes", "reasoning": "This bill directs the Secretary of State to study elections and submit findings with possible legislative recommendations by September 2027, sunsetting thereafter. It is a minimally prescriptive, low-cost study measure that enables evidence-based future election policy."},
  {"id": "SB1509", "vote": "yes", "reasoning": "This bill codifies the binding elector pledge requirement following the Supreme Court's 2020 Chiafalo v. Washington decision. It establishes a clear, orderly process for replacing any elector who casts an invalid ballot, strengthening the integrity of Oregon's electoral college participation."},
  {"id": "SB1510", "vote": "yes", "reasoning": "This is a technical cleanup bill that updates outdated federal tax terminology, aligns sunset dates for the earned income tax credit, expands film production tax credits to include commercials, and streamlines property tax exemption filing for affordable housing. All changes are relatively minor and administratively sensible."},
  {"id": "SB1511", "vote": "yes", "reasoning": "This bill requires the Legislative Revenue Officer to study Oregon's estate tax and review options for modifying the exemption threshold and tax rates, reporting findings by December 2027. It is a straightforward, low-cost study directive."},
  {"id": "SB1512", "vote": "yes", "reasoning": "This bill strengthens the Prosperity 10,000 workforce development program by shifting grant distribution to local workforce development boards, adding criteria for fund distribution, and removing an outdated minimum wage floor goal while retaining employment and completion metrics."},
  {"id": "SB1513", "vote": "yes", "reasoning": "This bill provides a temporary compliance extension until July 1, 2027 for real estate teams to comply with naming restrictions under ORS 696.370(5). Giving industry participants reasonable time to adapt to new regulatory requirements is sound policy, and the repeal mechanism ensures the extension is not permanent."},
  {"id": "SB1514", "vote": "no", "reasoning": "This bill repeals ORS 195.530, which established an objective reasonableness standard for local laws regulating public property use by people experiencing homelessness. Removing this statewide standard would leave homeless individuals without a consistent legal framework to challenge potentially arbitrary local ordinances."},
  {"id": "SB1515", "vote": "yes", "reasoning": "This bill strengthens protections for wrongfully convicted individuals by improving compensation processes, clarifying evidentiary standards, mandating certificates of innocence, and creating a post-conviction relief pathway for convictions based on now-discredited forensic science like bite mark analysis and hair microscopy."},
  {"id": "SB1516", "vote": "yes", "reasoning": "This bill addresses two legitimate public safety concerns: it expands aggravated harassment to cover electronic threats against public officials made in connection with their duties, and it clarifies that standing pretrial release orders do not override a magistrate's authority to weigh release criteria including community safety."},
  {"id": "SB1517", "vote": "yes", "reasoning": "This bill balances the interests of ski area operators and skiers by permitting liability releases only for ordinary negligence during the act of skiing, while explicitly prohibiting releases for gross negligence, equipment-related injuries, and violations of statutory duties. The required opt-out option protects consumers."},
  {"id": "SB1518", "vote": "yes", "reasoning": "This bill simply directs the Bureau of Labor and Industries to study worker protection issues and report findings by September 2027, with a sunset clause in 2028. A study mandate with a reporting deadline is a low-cost, evidence-based approach to informing future legislation."},
  {"id": "SB1519", "vote": "yes", "reasoning": "This bill restructures temporary total disability compensation to be more progressive — paying 75% of wages up to 75% of the state average weekly wage and 65% above that threshold — which provides relatively higher replacement rates for lower-wage workers."},
  {"id": "SB1520", "vote": "yes", "reasoning": "This bill authorizes the Employment Department Director to adopt administrative rules establishing an accounting system for the Paid Family and Medical Leave Insurance Fund to ensure tax compliance, without altering contribution rates or benefit levels."},
  {"id": "SB1521", "vote": "yes", "reasoning": "This bill enables inclusionary zoning in the Portland metro area while requiring cities and counties to offset developers' expected losses when mandating affordable units, ensuring that affordable housing requirements are economically viable and do not inadvertently suppress housing supply."},
  {"id": "SB1522", "vote": "yes", "reasoning": "This bill directs the Housing and Community Services Department to study housing issues and report to the Legislature by September 2027, with a sunset clause in 2028. Evidence-based policymaking requires robust research."},
  {"id": "SB1523", "vote": "yes", "reasoning": "This bill protects tenants who lack digital access or prefer not to use online portals by requiring landlords to offer alternatives to tenant portals and prohibiting mandatory electronic-only payments. These protections are equitable and proportionate."},
  {"id": "SB1524", "vote": "no", "reasoning": "This bill creates a continuing lottery revenue allocation specifically for horse racing events and infrastructure. Dedicating public lottery funds to a narrow private industry is poor fiscal policy that reduces flexibility for higher-priority public needs."},
  {"id": "SB1525", "vote": "yes", "reasoning": "This bill establishes a Blue Economy Task Force to study Oregon's coastal and ocean economic sectors and allows the Oregon Ocean Science Trust to form a nonprofit. The task force includes diverse stakeholders, has a clear reporting deadline, and sunsets automatically."},
  {"id": "SB1526", "vote": "yes", "reasoning": "This bill directs ODOE to seek grant funding (minimum $2 million) before incurring any state costs, and only then convenes a founding board to form a nonprofit entity for financing clean energy and resilience projects. The contingent structure is fiscally responsible."},
  {"id": "SB1527", "vote": "yes", "reasoning": "Eliminating cost-sharing on cervical cancer screenings and follow-up examinations removes a well-documented financial barrier to early cancer detection. The bill aligns coverage requirements with USPSTF grade A/B recommendations."},
  {"id": "SB1528", "vote": "no", "reasoning": "This bill directs OHA to 'study health care' with no defined scope, methodology, specific questions, or stakeholder process — it is a placeholder bill with essentially no substantive content. Mandating a vague study without parameters is unlikely to produce actionable findings."},
  {"id": "SB1529", "vote": "no", "reasoning": "SB1529 is substantively identical to SB1528 — it directs OHA to 'study health care' with no defined scope or methodology. Duplicating an already vague study mandate adds no value and unnecessarily burdens OHA."},
  {"id": "SB1530", "vote": "yes", "reasoning": "Expanding the crime of aggravated harassment to cover credible threats against public officials made because of their official duties addresses a genuine and growing public safety concern. The bill sets a reasonable threshold requiring the threat to be one that would reasonably cause alarm."},
  {"id": "SB1531", "vote": "yes", "reasoning": "This bill requires OHA to study the feasibility of funding emergency medical services through a universal health care model, an important policy question given EMS funding gaps across rural Oregon. The scope is specific and the timeline is reasonable."},
  {"id": "SB1532", "vote": "yes", "reasoning": "This bill makes targeted improvements to protections for vulnerable Oregonians in long-term care and I/DD services: adding procedural safeguards for license conditions, requiring consent forms for electronic monitoring, and modifying child placement and restraint provisions."},
  {"id": "SB1533", "vote": "yes", "reasoning": "This bill substantially strengthens the Oregon Foster Children's Bill of Rights with concrete, enforceable rights — including requiring rights documents within seven days of placement and presuming sibling contact unless a court orders otherwise with written findings."},
  {"id": "SB1534", "vote": "yes", "reasoning": "SB1534 addresses services for vulnerable persons in long-term care and related settings, strengthening protections and oversight mechanisms. The emergency declaration indicates time-sensitive implementation needs."},
  {"id": "SB1535", "vote": "no", "reasoning": "Like SB1528 and SB1529, this bill directs a state agency to 'study child care' with no defined scope, research questions, or methodology. An open-ended mandate to study it produces little of value compared to a targeted study."},
  {"id": "SB1536", "vote": "yes", "reasoning": "Directing ODE to study the adequacy of assessments in Oregon public schools is a well-targeted and timely mandate. Educational assessment adequacy is a concrete, answerable research question with a sunset provision."},
  {"id": "SB1537", "vote": "yes", "reasoning": "This bill improves transparency and accountability for community college boards by requiring publicly posted email addresses and adding a nonvoting student representative. Including a student voice on the board is a low-cost, high-benefit reform."},
  {"id": "SB1538", "vote": "yes", "reasoning": "This bill protects all students' right to access public education regardless of immigration or citizenship status, consistent with longstanding constitutional precedent under Plyler v. Doe. It also adds sensible guardrails around how schools respond to immigration enforcement actions."},
  {"id": "SB1539", "vote": "yes", "reasoning": "This bill removes an unnecessary licensing barrier for trained individuals to verify cattle pregnancy, a practical agricultural task that does not require full veterinary licensure. The State Department of Agriculture retains rule-making authority."},
  {"id": "SB1540", "vote": "yes", "reasoning": "Oregon faces a serious wildfire insurance availability and affordability crisis, and this bill directly addresses it by requiring insurers to disclose how they use wildfire risk models and to reward policyholders who take mitigation actions."},
  {"id": "SB1541", "vote": "yes", "reasoning": "This bill takes a polluter-pays approach to climate change by holding major fossil fuel companies strictly liable for a proportionate share of Oregon's climate-related costs. Directing funds toward climate resilience projects, with a 40 percent floor for environmental justice communities, aligns financial accountability with the communities bearing the greatest climate burdens."},
  {"id": "SB1542", "vote": "yes", "reasoning": "This bill brings meaningful discipline to Oregon's transportation investment process by requiring a 10-year capital investment plan with a transparent, rules-based project scoring methodology that prioritizes safety and preservation over capacity expansion."},
  {"id": "SB1543", "vote": "yes", "reasoning": "Expanding the Oregon Transportation Commission to include legislative nonvoting members and requiring a debt financing management policy with a 20 percent debt service cap adds needed oversight and fiscal discipline to highway bonding."},
  {"id": "SB1544", "vote": "yes", "reasoning": "This is a modest, low-cost study bill directing ODOT to examine uniform standards for speed bumps, which vary widely in Oregon and can create safety hazards for cyclists, motorcyclists, and emergency vehicles."},
  {"id": "SB1545", "vote": "yes", "reasoning": "Corner crossing has been a contentious access issue in the American West, and this bill provides a sensible legal resolution. It grants trespass immunity only when the crosser does not damage property or disturb the landowner's use."},
  {"id": "SB1546", "vote": "yes", "reasoning": "The harms caused by AI companion platforms — particularly to minors and vulnerable users — are well-documented. Requiring clear AI disclosure, evidence-based suicide detection protocols, and heightened protections for minors addresses genuine public health concerns."},
  {"id": "SB1547", "vote": "yes", "reasoning": "Creating a licensed behavioral health and wellness practitioner credential will help expand Oregon's behavioral health workforce, particularly for early identification, prevention, and brief intervention services where shortages are acute."},
  {"id": "SB1548", "vote": "yes", "reasoning": "Individually wrapping cannabinoid edibles, capping single-unit potency at 10 mg, requiring comprehensive health warning labels, and allowing local governments to establish larger buffer zones are all proportionate public health measures."},
  {"id": "SB1549", "vote": "no", "reasoning": "This bill increases the political contribution tax credit from $50/$100 to $1,000/$2,000 — a 20-fold increase. While political participation tax credits have merit, this dramatic increase primarily benefits wealthier donors and effectively subsidizes large political contributions at taxpayer expense."},
  {"id": "SB1550", "vote": "yes", "reasoning": "This bill addresses a real and well-documented problem: domestic violence homicides are sometimes staged to appear as suicides or accidents. Requiring law enforcement to interview family members and request autopsies when multiple red flags are present is a measured and evidence-based reform."},
  {"id": "SB1551", "vote": "yes", "reasoning": "With wildfire risk increasing across Oregon, homeowners should not be blocked by HOA rules or deed restrictions from installing fire-hardened building materials. This bill strikes a reasonable balance by invalidating overly restrictive HOA rules while still allowing reasonable aesthetic standards."},
  {"id": "SB1552", "vote": "yes", "reasoning": "Deed fraud and title theft are serious and growing problems in Oregon. Requiring county clerks to notify property owners when documents affecting their title are recorded is a low-cost, effective consumer protection measure."},
  {"id": "SB1553", "vote": "yes", "reasoning": "This bill holds negligent electric utilities accountable for wildfire costs without shifting those costs onto ratepayers. The escrow requirement ensures judgments can actually be paid, and directing punitive damages to a Wildfire Recovery Fund adds public benefit."},
  {"id": "SB1554", "vote": "no", "reasoning": "While ensuring medical care for infants born alive is a legitimate goal, this bill is drafted in a politically charged manner that conflates abortion with viable live birth emergencies and creates private rights of action that could be weaponized to harass medical providers. Existing law already addresses these situations."},
  {"id": "SB1555", "vote": "yes", "reasoning": "This bill modernizes Oregon's constitutionally required public education funding reporting process by replacing an outdated committee structure with a cost-model methodology and abolishing the underperforming Quality Education Commission."},
  {"id": "SB1556", "vote": "yes", "reasoning": "Consolidating and clarifying the rules for non-attorney representation in the Oregon Tax Court's magistrate division is a sensible housekeeping measure requested by the judiciary. It improves access to justice without undermining proceedings."},
  {"id": "SB1557", "vote": "yes", "reasoning": "This judicial-department-requested bill modernizes contempt proceedings by clarifying procedural requirements, adding default judgment procedures, establishing venue rules, and better protecting defendants' rights including notice of right to counsel."},
  {"id": "SB1558", "vote": "yes", "reasoning": "This bill makes practical adjustments to Oregon's nurse staffing law, including allowing type C (small rural) hospitals to seek committee-approved variances and clarifying when statutory ratios apply as the default plan. The moratorium on penalties until July 2027 allows for an orderly transition."},
  {"id": "SB1559", "vote": "no", "reasoning": "This bill directs the Oregon Health Authority to 'study health care' with no further specification of scope, methodology, or purpose. This is an extremely vague mandate that provides no meaningful direction to the agency."},
  {"id": "SB1560", "vote": "no", "reasoning": "While religious land use protections are important, this bill removes counties' existing ability to apply reasonable physical-characteristic regulations to places of worship. Eliminating all site and design review authority goes beyond protecting religious exercise."},
  {"id": "SB1561", "vote": "yes", "reasoning": "Homeowners who lose their dwellings to wildfire, flood, or other involuntary causes should be able to rebuild without being trapped in lengthy land use processes. This bill creates a streamlined approval pathway with clear criteria."},
  {"id": "SB1562", "vote": "yes", "reasoning": "Changing the transient lodging tax split from 70/30 tourism-to-services to 40/60 gives local governments much more flexibility to use hotel tax revenue for essential services. The biennial reporting requirement adds transparency."},
  {"id": "SB1563", "vote": "yes", "reasoning": "Oregon currently lacks a state-law analogue to 42 U.S.C. § 1983 allowing civil rights suits against state actors. This bill fills that gap by allowing persons deprived of Oregon constitutional rights to sue for damages and injunctive relief."},
  {"id": "SB1564", "vote": "yes", "reasoning": "Adding land to Woodburn's urban growth boundary to accommodate at least 600 residential units, with 30 percent required to be affordable for 60 years, is exactly the kind of targeted infill-expansion policy Oregon needs to address its housing shortage."},
  {"id": "SB1565", "vote": "yes", "reasoning": "Increasing snowmobile registration fees from $10 to $30 — the first increase in many years — at the request of the Oregon State Snowmobile Association is a user-fee adjustment that is both modest and appropriate for funding trail maintenance."},
  {"id": "SB1566", "vote": "yes", "reasoning": "Exempting affordable housing projects from prevailing wage requirements under carefully defined criteria addresses a real barrier to affordable housing production. Given Oregon's severe housing shortage, easing construction costs for income-restricted housing serves an overriding public need."},
  {"id": "SB1567", "vote": "yes", "reasoning": "Creating a mixed income housing loan program through OHCS, with a revolving loan fund for developments that include both market-rate and income-restricted units, is a creative tool to leverage private capital for affordable housing production."},
  {"id": "SB1568", "vote": "yes", "reasoning": "Establishing minimum doula coverage standards and requiring coverage for lactation counselors addresses documented disparities in maternal and infant health outcomes, particularly for communities of color. Doula and lactation support are evidence-based interventions."},
  {"id": "SB1569", "vote": "yes", "reasoning": "Extending PERS police officer status to juvenile court counselors, forensic scientists, evidence technicians, and other law-enforcement-adjacent roles recognizes that these positions involve meaningful public safety responsibilities. The prospective-only application is fiscally responsible."},
]

# Build vote lookup
vote_map = {v["id"]: {"vote": v["vote"], "reasoning": v["reasoning"]} for v in votes}

# Load and update bills
bills = json.loads(DATA_FILE.read_text())
for bill in bills:
    if bill["id"] in vote_map:
        bill["vote"] = vote_map[bill["id"]]

DATA_FILE.write_text(json.dumps(bills, indent=2))

yes_count = sum(1 for b in bills if b["vote"]["vote"] == "yes")
no_count = sum(1 for b in bills if b["vote"]["vote"] == "no")
print(f"Updated {len(vote_map)} votes: {yes_count} yes, {no_count} no")
